/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2017
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 17/03/2015 1:13:29 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package reika.chromaticraft.models;

import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;

import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;

public final class ModelFarmer {
    private final ModelPart root;

    public ModelFarmer(ModelPart root) { this.root = root; }

    public void render(PoseStack pose, VertexConsumer output, int light, int overlay) {
        root.render(pose, output, light, overlay);
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        var root = mesh.getRoot();
        root.addOrReplaceChild("Shape1", CubeListBuilder.create().texOffs(0, 0).mirror()
                .addBox(0F, 0F, 0F, 16, 3, 16), PartPose.offsetAndRotation(-8F, 8F, -8F, 0F, 0F, 0F));
        root.addOrReplaceChild("Shape2", CubeListBuilder.create().texOffs(92, 0).mirror()
                .addBox(0F, 0F, 0F, 2, 10, 2), PartPose.offsetAndRotation(6F, 11F, 6F, 0F, 0F, 0F));
        root.addOrReplaceChild("Shape1b", CubeListBuilder.create().texOffs(0, 71).mirror()
                .addBox(0F, 0F, 0F, 16, 3, 16), PartPose.offsetAndRotation(-8F, 21F, -8F, 0F, 0F, 0F));
        root.addOrReplaceChild("Shape2b", CubeListBuilder.create().texOffs(74, 0).mirror()
                .addBox(0F, 0F, 0F, 2, 10, 2), PartPose.offsetAndRotation(-8F, 11F, 6F, 0F, 0F, 0F));
        root.addOrReplaceChild("Shape2c", CubeListBuilder.create().texOffs(83, 0).mirror()
                .addBox(0F, 0F, 0F, 2, 10, 2), PartPose.offsetAndRotation(6F, 11F, -8F, 0F, 0F, 0F));
        root.addOrReplaceChild("Shape2d", CubeListBuilder.create().texOffs(65, 0).mirror()
                .addBox(0F, 0F, 0F, 2, 10, 2), PartPose.offsetAndRotation(-8F, 11F, -8F, 0F, 0F, 0F));
        root.addOrReplaceChild("Shape3", CubeListBuilder.create().texOffs(0, 33).mirror()
                .addBox(-1F, 0F, 0F, 1, 10, 12), PartPose.offsetAndRotation(8F, 11F, -6F, 0F, -0.2617994F, 0F));
        root.addOrReplaceChild("Shape3b", CubeListBuilder.create().texOffs(0, 20).mirror()
                .addBox(0F, 0F, 0F, 12, 10, 1), PartPose.offsetAndRotation(-6F, 11F, -7F, 0F, 0F, 0F));
        root.addOrReplaceChild("Shape3c", CubeListBuilder.create().texOffs(0, 33).mirror()
                .addBox(0F, 0F, 0F, 1, 10, 12), PartPose.offsetAndRotation(-8F, 11F, -6F, 0F, 0.2617994F, 0F));
        root.addOrReplaceChild("Shape4", CubeListBuilder.create().texOffs(27, 54).mirror()
                .addBox(0F, 0F, 0F, 2, 10, 6), PartPose.offsetAndRotation(-1F, 11F, 1F, 0F, 0F, 0F));
        root.addOrReplaceChild("Shape4d", CubeListBuilder.create().texOffs(0, 56).mirror()
                .addBox(0F, 0F, 0F, 12, 10, 1), PartPose.offsetAndRotation(-6F, 11F, 7F, 0F, 0F, 0F));
        return LayerDefinition.create(mesh, 128, 128);
    }
}
