package reika.chromaticraft.world.dimension.structure;

import java.util.HashSet;
import java.util.Set;

import com.mojang.serialization.MapCodec;

import net.minecraft.core.BlockPos;
import net.minecraft.core.Vec3i;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.LevelReader;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.Rotation;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.levelgen.structure.templatesystem.StructurePlaceSettings;
import net.minecraft.world.level.levelgen.structure.templatesystem.StructureProcessor;
import net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate;

import reika.chromaticraft.ChromatiCraft;
import reika.chromaticraft.block.worldgen26.BlockStructureShield;
import reika.chromaticraft.data.ChromaStructureTemplateProvider;
import reika.chromaticraft.registry.ChromaBlocks;
import reika.chromaticraft.registry.ChromaShieldTypes;

/**
 * One-time repair for monuments generated by the pre-parity 26.2 port.
 *
 * <p>That port read the obsolete, commented-out V33a gold table as live completion data and omitted
 * the real unconditional ring. It also allowed Proxima's login safety capsule to carve through a
 * monument. Both leave an existing world permanently unable to pass the ritual unless the authored
 * template and inlay are repaired in place.
 */
public final class MonumentIntegrity {

	public static final int CURRENT_LAYOUT_VERSION = 1;

	private MonumentIntegrity() {}

	public static boolean repairLegacyLayout(ServerLevel level, BlockPos controllerPos) {
		BlockPos anchor = controllerPos.subtract(MonumentPiece.CONTROLLER_OFFSET);
		StructureTemplate template = level.getStructureManager()
				.get(ChromaStructureTemplateProvider.PROXIMA_MONUMENT).orElse(null);
		if (template == null) {
			ChromatiCraft.LOGGER.error("Cannot repair monument at {}: template {} is missing",
					controllerPos, ChromaStructureTemplateProvider.PROXIMA_MONUMENT);
			return false;
		}

		Set<BlockPos> damagedMinerals = new HashSet<>();
		for (MonumentMineralBlocks.Cell cell : MonumentMineralBlocks.expected()) {
			BlockPos at = anchor.offset(cell.offset());
			BlockState current = level.getBlockState(at);
			if (current.isAir() || isSafetyCloak(current) || current.is(Blocks.GOLD_BLOCK))
				damagedMinerals.add(at);
		}

		RepairProcessor processor = new RepairProcessor(level, anchor);
		StructurePlaceSettings settings = new StructurePlaceSettings().setRotation(Rotation.NONE)
				.setIgnoreEntities(true).addProcessor(processor);
		template.placeInWorld(level, anchor, anchor, settings,
				net.minecraft.util.RandomSource.create(controllerPos.asLong()), 3);

		Set<BlockPos> fixedGold = new HashSet<>();
		for (Vec3i offset : MonumentMineralBlocks.fixedGold()) {
			BlockPos at = anchor.offset(offset);
			fixedGold.add(at);
			level.setBlock(at, Blocks.GOLD_BLOCK.defaultBlockState(), 3);
		}

		// Remove safety-capsule shell blocks from authored air, and erase the obsolete gold ring where
		// it fell outside the sparse monument template. Authored cloak cells are retained by the set.
		Vec3i size = template.getSize();
		for (int x = 0; x < size.getX(); x++) {
			for (int y = 0; y < size.getY(); y++) {
				for (int z = 0; z < size.getZ(); z++) {
					BlockPos at = anchor.offset(x, y, z);
					BlockState current = level.getBlockState(at);
					if (isSafetyCloak(current) && !processor.authored.contains(at))
						level.setBlock(at, Blocks.AIR.defaultBlockState(), 3);
					else if (y == 0 && current.is(Blocks.GOLD_BLOCK) && !fixedGold.contains(at)
							&& !damagedMinerals.contains(at))
						level.setBlock(at, Blocks.AIR.defaultBlockState(), 3);
				}
			}
		}

		// If the safety capsule erased a player-completed inlay cell, restoring only the underlying
		// template would silently turn it back into Structure Stone. The expected mineral is the only
		// recoverable and ritual-correct state for such a damaged cell.
		for (MonumentMineralBlocks.Cell cell : MonumentMineralBlocks.expected()) {
			BlockPos at = anchor.offset(cell.offset());
			if (damagedMinerals.contains(at))
				level.setBlock(at, cell.mineral().block().defaultBlockState(), 3);
		}
		ChromatiCraft.LOGGER.info("Repaired legacy monument layout at {}: restored {} damaged inlay cells and installed {} fixed gold blocks",
				controllerPos, damagedMinerals.size(), fixedGold.size());
		return true;
	}

	private static boolean isSafetyCloak(BlockState state) {
		return state.is(ChromaBlocks.shielding(ChromaShieldTypes.CLOAK).get())
				&& (!state.hasProperty(BlockStructureShield.REINFORCED)
						|| !state.getValue(BlockStructureShield.REINFORCED));
	}

	private static final class RepairProcessor implements StructureProcessor {
		private static final MapCodec<RepairProcessor> CODEC =
				MapCodec.unit(RepairProcessor::new);
		private final Set<BlockPos> authored = new HashSet<>();
		private ServerLevel server;
		private BlockPos anchor;

		private RepairProcessor() {}

		private RepairProcessor(ServerLevel level, BlockPos origin) {
			server = level;
			anchor = origin;
		}

		@Override
		public StructureTemplate.StructureBlockInfo processBlock(LevelReader level,
				BlockPos targetPosition, BlockPos referencePos, BlockPos templateRelativePos,
				StructureTemplate.StructureBlockInfo processedBlockInfo,
				StructurePlaceSettings settings) {
			BlockPos at = processedBlockInfo.pos();
			authored.add(at.immutable());
			BlockState current = server.getBlockState(at);
			boolean wrongGold = current.is(Blocks.GOLD_BLOCK)
					&& !MonumentMineralBlocks.fixedGold().contains(templateRelativePos);
			boolean capsuleDamage = current.isAir()
					|| isSafetyCloak(current) && !current.is(processedBlockInfo.state().getBlock());
			return wrongGold || capsuleDamage ? processedBlockInfo : null;
		}

		@Override
		public MapCodec<RepairProcessor> codec() {
			return CODEC;
		}
	}
}
